server:
  port: 8083
spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/bookon-user
    username: user
    password: user
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true