version: "3.8"

services:
  mongo-book:
    image: mongo:latest
    container_name: mongo-book
    hostname: bookonbook
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: book
      MONGO_INITDB_ROOT_PASSWORD: book
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/bookon-book --quiet
      start_period: 10s
    volumes:
      - ./data/book/mongo:/data/db
      - ./docker/book/mongo:/docker-entrypoint-initdb.d
    # DIVIDA TECNICA
    #command: ./docker/book/mongo/v1_user.sh
    ports:
      - "27017:27017"
    networks:
      - bookon-network

  mongo-loan:
    image: mongo:latest
    container_name: mongo-loan
    hostname: bookon-loan
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: loan
      MONGO_INITDB_ROOT_PASSWORD: loan
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27020/bookon-loan --quiet
      start_period: 10s
    volumes:
      - ./data/loan/mongo/:/data/db
      - ./docker/loan/mongo:/docker-entrypoint-initdb.d
    ports:
      - "27020:27017"
    networks:
      - bookon-network

  mongo-express-book:
    image: mongo-express
    container_name: mongo-express-book
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: book
      ME_CONFIG_MONGODB_ADMINPASSWORD: book
      ME_CONFIG_MONGODB_SERVER: bookonbook
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: adminpassword
    ports:
      - "8888:8081"
    networks:
      - bookon-network

  mongo-express-loan:
    image: mongo-express
    container_name: mongo-express-loan
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: loan
      ME_CONFIG_MONGODB_ADMINPASSWORD: loan
      ME_CONFIG_MONGODB_SERVER: bookon-loan
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: adminpassword
    ports:
      - "8889:8081"
    networks:
      - bookon-network

  postgresql-user:
    image: postgres:latest
    container_name: postgresql-user
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: bookon-user
    ports:
      - "5432:5432"
    volumes:
      - ./data/user/postgresql:/var/lib/postgresql/data
      - ./docker/user/postgresql:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d bookon-user" ]  # Verifica se é possível se conectar ao banco de dados
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - bookon-network

networks:
  bookon-network:
    driver: bridge
