server:
   port: 8081
   error:
      include-message: ALWAYS
      include-binding-errors: ALWAYS
      include-stacktrace: NEVER
      include-exception: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookon
    username: server
    password: server
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    
    
  mail:
    host: smtp.gmail.com # Endereço do servidor SMTP
    port: 587 # Porta do servidor SMTP (587 é comum para TLS, 465 para SSL)
    username: kauanrocha.professional@gmail.com # Seu nome de usuário de e-mail
    password: bwvm zikc nmuz tzod # Sua senha de e-mail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # Use true para TLS, false para SSL
          ssl:
            trust: smtp.gmail.com # Use o nome do host SMTP ou "true" para confiança em todos os hosts
    default-encoding: UTF-8 # Codificação padrão para mensagens
