server:
  port: 8084
spring:
  application:
    name: loan
  data:
    mongodb:
      host: localhost
      port: 27020
      database: bookon-loan
      username: loan
      password: loan
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true