server:
  port: 8082
spring:
  application:
    name: book
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookonbook
      username: book
      password: book
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
